import { Router } from 'express';
import { lessonRouter } from './lesson.routes.js';
import { alertRouter, targetRouter } from './alert.routes.js';
import { analyticsRouter } from './analytics.routes.js';
import { attendanceRouter, attendanceSessionRouter } from './attendance.routes.js';
import { auditRouter } from './audit.routes.js';
import { authRouter } from './auth.routes.js';
import { callRouter } from './call.routes.js';
import { commissionRouter } from './commission.routes.js';
import { documentRouter } from './document.routes.js';
import { employeeRouter } from './employee.routes.js';
import { recurringExpenseRouter } from './recurringExpense.routes.js';
import { branchRouter } from './branch.routes.js';
import { portalRouter } from './portal.routes.js';
import { certificateRouter } from './certificate.routes.js';
import { discountRouter, referralRouter } from './discount.routes.js';
import { feedbackRouter } from './feedback.routes.js';
import { inventoryRouter } from './inventory.routes.js';
import { aiRouter } from './ai.routes.js';
import { automationRouter } from './automation.routes.js';
import { curriculumRouter } from './curriculum.routes.js';
import { questionRouter } from './question.routes.js';
import { roomRouter } from './room.routes.js';
import { telegramRouter } from './telegram.routes.js';
import { courseRouter } from './course.routes.js';
import { dashboardRouter } from './dashboard.routes.js';
import { expenseRouter, financeRouter, incomeRouter } from './finance.routes.js';
import { followUpRouter } from './followUp.routes.js';
import { gamificationRouter } from './gamification.routes.js';
import { groupRouter } from './group.routes.js';
import { examRouter, homeworkRouter, rubricRouter } from './homework.routes.js';
import { healthRouter } from './health.routes.js';
import { leadRouter } from './lead.routes.js';
import { lookupRouter } from './lookup.routes.js';
import { debtRouter, paymentRouter } from './payment.routes.js';
import { parentRouter } from './parent.routes.js';
import { notificationRouter } from './notification.routes.js';
import { permissionRouter, roleRouter } from './role.routes.js';
import { reportRouter } from './report.routes.js';
import { searchRouter } from './search.routes.js';
import { studentRouter } from './student.routes.js';
import { payrollRouter, salaryRouter, teacherRouter } from './teacher.routes.js';
import { userRouter } from './user.routes.js';
import { masteryRouter } from './mastery.routes.js';
import { teachingRouter } from './teaching.routes.js';
import { academicAnalyticsRouter } from './academicAnalytics.routes.js';
import { taskRouter } from './task.routes.js';
import { publicRouter, settingsRouter } from './settings.routes.js';

/** Barcha modul routerlari shu yerda `/api` ostiga ulanadi. */
export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/public', publicRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/roles', roleRouter);
apiRouter.use('/permissions', permissionRouter);
apiRouter.use('/dashboard', dashboardRouter);
// `/analytics/academic` umumiy analitikadan oldin: o'qituvchi ham kiradi (ruxsat boshqacha)
apiRouter.use('/analytics/academic', academicAnalyticsRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/alerts', alertRouter);
apiRouter.use('/targets', targetRouter);
apiRouter.use('/leads', leadRouter);
apiRouter.use('/calls', callRouter);
apiRouter.use('/follow-ups', followUpRouter);
apiRouter.use('/branches', branchRouter);
apiRouter.use('/portal', portalRouter);
apiRouter.use('/certificates', certificateRouter);
apiRouter.use('/discounts', discountRouter);
apiRouter.use('/referrals', referralRouter);
apiRouter.use('/feedback', feedbackRouter);
apiRouter.use('/products', inventoryRouter);
apiRouter.use('/ai', aiRouter);
apiRouter.use('/automation', automationRouter);
apiRouter.use('/lessons', lessonRouter);
apiRouter.use('/curriculum', curriculumRouter);
apiRouter.use('/questions', questionRouter);
apiRouter.use('/rooms', roomRouter);
apiRouter.use('/telegram', telegramRouter);
apiRouter.use('/courses', courseRouter);
apiRouter.use('/groups', groupRouter);
apiRouter.use('/students', studentRouter);
apiRouter.use('/parents', parentRouter);
apiRouter.use('/attendance', attendanceRouter);
apiRouter.use('/attendance-sessions', attendanceSessionRouter);
apiRouter.use('/homework', homeworkRouter);
apiRouter.use('/rubrics', rubricRouter);
apiRouter.use('/exams', examRouter);
apiRouter.use('/mastery', masteryRouter);
apiRouter.use('/teaching', teachingRouter);
apiRouter.use('/tasks', taskRouter);
apiRouter.use('/gamification', gamificationRouter);
apiRouter.use('/teachers', teacherRouter);
apiRouter.use('/salaries', salaryRouter);
apiRouter.use('/teacher-commissions', commissionRouter);
apiRouter.use('/payroll', payrollRouter);
apiRouter.use('/employees', employeeRouter);
apiRouter.use('/documents', documentRouter);
apiRouter.use('/recurring-expenses', recurringExpenseRouter);
apiRouter.use('/finance', financeRouter);
apiRouter.use('/incomes', incomeRouter);
apiRouter.use('/expenses', expenseRouter);
apiRouter.use('/payments', paymentRouter);
apiRouter.use('/debts', debtRouter);
apiRouter.use('/reports', reportRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/audit-logs', auditRouter);
apiRouter.use('/lookups', lookupRouter);
