/** Audit jurnalidagi amallar uchun o‘zbekcha izohlar */
export const AUDIT_ACTION_LABELS: Record<string, string> = {
  'auth.login': 'Tizimga kirdi',
  'auth.login_failed': 'Kirish muvaffaqiyatsiz',
  'auth.login_locked': 'Hisob vaqtincha bloklandi (ko‘p noto‘g‘ri urinish)',
  'auth.logout': 'Tizimdan chiqdi',
  'auth.logout_all': 'Barcha qurilmalardan chiqdi',
  'auth.password_changed': 'Parolini o‘zgartirdi',
  'auth.password_reset': 'Parolni tikladi',
  'auth.password_reset_requested': 'Parolni tiklashni so‘radi',
  'auth.refresh_token_reuse': 'Shubhali token qayta ishlatildi',

  'user.registered': 'Ro‘yxatdan o‘tdi',
  'user.created': 'Xodim qo‘shildi',
  'user.updated': 'Xodim ma’lumoti o‘zgardi',
  'user.status_changed': 'Xodim holati o‘zgardi',
  'user.deleted': 'Xodim o‘chirildi',
  'user.password_reset_by_admin': 'Admin parolni yangiladi',

  'role.created': 'Rol yaratildi',
  'role.updated': 'Rol o‘zgartirildi',
  'role.permissions_updated': 'Rol ruxsatlari yangilandi',
  'role.deleted': 'Rol o‘chirildi',

  'lead.created': 'Lead qo‘shildi',
  'lead.updated': 'Lead tahrirlandi',
  'lead.status_changed': 'Lead statusi o‘zgardi',
  'lead.assigned': 'Lead biriktirildi',
  'lead.deleted': 'Lead o‘chirildi',

  'call.created': 'Qo‘ng‘iroq qayd etildi',
  'call.updated': 'Qo‘ng‘iroq tahrirlandi',
  'call.deleted': 'Qo‘ng‘iroq o‘chirildi',

  'followup.created': 'Follow-up yaratildi',
  'followup.updated': 'Follow-up tahrirlandi',
  'followup.completed': 'Follow-up bajarildi',
  'followup.deleted': 'Follow-up o‘chirildi',

  'branch.created': 'Filial qo‘shildi',
  'lead.auto_assigned': 'Lead avtomatik biriktirildi',
  'lead.assignment_rules_updated': 'Lead taqsimot qoidalari o‘zgartirildi',
  'employee.leave_requested': 'Ta’til arizasi qo‘shildi',
  'employee.leave_approved': 'Ta’til tasdiqlandi',
  'employee.leave_rejected': 'Ta’til arizasi rad etildi',
  'employee.leave_cancelled': 'Ta’til bekor qilindi',
  'payment.intent_created': 'Onlayn to‘lov so‘rovi yaratildi',
  'payment.online_received': 'Onlayn to‘lov qabul qilindi',
  'automation.rule_updated': 'Avtomatlashtirish qoidasi o‘zgartirildi',
  'inventory.product_created': 'Mahsulot qo‘shildi',
  'inventory.product_updated': 'Mahsulot tahrirlandi',
  'inventory.category_saved': 'Mahsulot turkumi saqlandi',
  'inventory.stock_moved': 'Ombor harakati yozildi',
  'feedback.created': 'Fikr qo‘shildi',
  'feedback.handled': 'Salbiy fikr ishlandi',
  'discount.granted': 'Chegirma berildi',
  'discount.revoked': 'Chegirma bekor qilindi',
  'discount.rule_saved': 'Chegirma qoidasi saqlandi',
  'discount.settings_updated': 'Chegirma sozlamalari o‘zgartirildi',
  'discount.promo_created': 'Promo kod yaratildi',
  'discount.promo_enabled': 'Promo kod yoqildi',
  'discount.promo_disabled': 'Promo kod o‘chirildi',
  'referral.rewarded': 'Taklif uchun bonus berildi',
  'referral.cancelled': 'Taklif bekor qilindi',
  'certificate.issued': 'Sertifikat berildi',
  'certificate.revoked': 'Sertifikat bekor qilindi',
  'question.created': 'Savol qo‘shildi',
  'question.updated': 'Savol tahrirlandi',
  'exam.questions_attached': 'Imtihonga savollar biriktirildi',
  'exam.attempt_submitted': 'Imtihon javoblari qabul qilindi',
  'exam.attempt_graded': 'Imtihon urinishi baholandi',
  'curriculum.module_created': 'Kurs moduli qo‘shildi',
  'curriculum.module_updated': 'Kurs moduli tahrirlandi',
  'curriculum.topic_created': 'Mavzu qo‘shildi',
  'curriculum.topic_updated': 'Mavzu tahrirlandi',
  'curriculum.topic_marked': 'Mavzu o‘tilgan deb belgilandi',
  'room.created': 'Xona qo‘shildi',
  'room.updated': 'Xona tahrirlandi',
  'portal.student_account_created': 'O‘quvchiga kabinet ochildi',
  'portal.parent_account_created': 'Ota-onaga kabinet ochildi',
  'branch.updated': 'Filial tahrirlandi',
  'course.created': 'Kurs qo‘shildi',
  'course.updated': 'Kurs tahrirlandi',
  'course.deleted': 'Kurs o‘chirildi',

  'group.created': 'Guruh qo‘shildi',
  'group.updated': 'Guruh tahrirlandi',
  'group.deleted': 'Guruh o‘chirildi',

  'student.created': 'O‘quvchi qo‘shildi',
  'student.updated': 'O‘quvchi tahrirlandi',
  'student.status_changed': 'O‘quvchi holati o‘zgardi',
  'student.deleted': 'O‘quvchi o‘chirildi',
  'student.converted_from_lead': 'Lead o‘quvchiga aylantirildi',

  'parent.created': 'Ota-ona qo‘shildi',
  'parent.updated': 'Ota-ona tahrirlandi',
  'parent.deleted': 'Ota-ona o‘chirildi',
  'parent.linked': 'Farzand biriktirildi',
  'parent.link_updated': 'Ota-ona bog‘lanishi o‘zgardi',
  'parent.unlinked': 'Farzand ajratildi',

  'attendance.marked': 'Davomat belgilandi',

  'homework.created': 'Uy vazifasi berildi',
  'homework.updated': 'Uy vazifasi tahrirlandi',
  'homework.graded': 'Uy vazifasi baholandi',
  'homework.deleted': 'Uy vazifasi o‘chirildi',

  'exam.created': 'Imtihon yaratildi',
  'exam.updated': 'Imtihon tahrirlandi',
  'exam.graded': 'Imtihon natijalari kiritildi',
  'exam.deleted': 'Imtihon o‘chirildi',

  'payment.created': 'To‘lov qabul qilindi',
  'telegram.linked': 'Telegram ulandi',
  'telegram.unlinked': 'Telegram uzildi',
  'payment.deleted': 'To‘lov bekor qilindi',
  'payment.refunded': 'To‘lov qaytarildi',
  'expense.requested': 'Xarajat tasdiqqa yuborildi',
  'document.uploaded': 'Hujjat (chek) biriktirildi',
  'document.updated': 'Hujjat ma’lumotlari o‘zgartirildi',
  'document.downloaded': 'Xodim hujjati yuklab olindi',
  'budget.copied': 'Budjet o‘tgan oydan nusxalandi',
  'alert.settings_updated': 'Ogohlantirish sozlamalari o‘zgartirildi',
  'audit.exported': 'Audit jurnali eksport qilindi',
  'document.deleted': 'Hujjat o‘chirildi',
  'expense.approved': 'Xarajat tasdiqlandi',
  'expense.rejected': 'Xarajat rad etildi',
  'expense.paid': 'Xarajat to‘landi',
  'expense.threshold_changed': 'Xarajat tasdiq chegarasi o‘zgartirildi',
  'expense.recurring_created': 'Takroriy xarajat qo‘shildi',
  'expense.recurring_updated': 'Takroriy xarajat o‘zgartirildi',
  'finance.period_closed': 'Moliyaviy oy yopildi',
  'finance.period_reopened': 'Moliyaviy oy qayta ochildi',

  'teacher.profile_created': 'O‘qituvchi profili yaratildi',
  'teacher.status_changed': 'O‘qituvchi holati o‘zgartirildi',
  'teacher.profile_updated': 'O‘qituvchi profili tahrirlandi',
  'teacher.deactivated': 'O‘qituvchi faolsizlantirildi',

  'salary.rule_created': 'Maosh modeli belgilandi',
  'salary.calculated': 'Maosh hisoblandi',
  'salary.adjusted': 'Bonus/jarima o‘zgartirildi',
  'salary.approved': 'Maosh tasdiqlandi',
  'salary.paid': 'Maosh to‘landi',
  'employee.created': 'Xodim qo‘shildi',
  'employee.updated': 'Xodim ma’lumotlari o‘zgartirildi',
  'salary.adjustment_added': 'Maoshga bonus/jarima qo‘shildi',
  'salary.adjustment_voided': 'Bonus/jarima bekor qilindi',
  'salary.advance_paid': 'Avans berildi',
  'salary.unlocked': 'Tasdiqlangan maosh qayta ochildi',
  'salary.note_updated': 'Maosh izohi o‘zgartirildi',
  'commission.reversed': 'O‘qituvchi foizi qaytarildi',
  'commission.carried_over': 'Manfiy foiz keyingi oyga ko‘chirildi',

  'finance.account_created': 'Kassa qo‘shildi',
  'finance.account_updated': 'Kassa tahrirlandi',
  'finance.transfer': 'Kassalar o‘rtasida o‘tkazma',
  'finance.transaction_voided': 'Moliyaviy yozuv bekor qilindi',
  'finance.category_created': 'Kategoriya qo‘shildi',
  'finance.category_updated': 'Kategoriya tahrirlandi',

  'income.created': 'Tushum qayd etildi',
  'income.voided': 'Tushum bekor qilindi',

  'expense.created': 'Xarajat qayd etildi',
  'expense.voided': 'Xarajat bekor qilindi',

  'budget.saved': 'Budjet saqlandi',

  'alert.resolved': 'Ogohlantirish yopildi',
  'target.updated': 'Sotuv rejasi belgilandi',
  'gamification.xp_awarded': 'XP berildi',
  'gamification.badge_awarded': 'Nishon berildi',
  'gamification.badge_updated': 'Nishon tahrirlandi',
  'gamification.level_updated': 'Daraja tahrirlandi',
  'gamification.rule_updated': 'XP qoidasi tahrirlandi',
  'gamification.recalculated': 'XP va darajalar qayta hisoblandi',
  'attendance_session.updated': 'Dars seansi tahrirlandi',
  'attendance_session.deleted': 'Dars seansi o‘chirildi',
  'payment_schedule.generated': 'To‘lov jadvali tuzildi',
  'payment_schedule.updated': 'To‘lov jadvali o‘zgartirildi',
  'student.group_changed': 'O‘quvchi guruhi almashtirildi',
};

export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  telegram_link: 'Telegram bog‘lanishi',
  /** Kirish/chiqish amallari ham foydalanuvchi obyektiga yoziladi */
  user: 'Xodim',
  audit: 'Audit jurnali',
  role: 'Rol',
  lead: 'Lead',
  call: 'Qo‘ng‘iroq',
  followUp: 'Follow-up',
  branch: 'Filial',
  room: 'Xona',
  course: 'Kurs',
  group: 'Guruh',
  student: 'O‘quvchi',
  parent: 'Ota-ona',
  payment: 'To‘lov',
  debt: 'Qarzdorlik',
  attendance: 'Davomat',
  homework: 'Uy vazifasi',
  exam: 'Imtihon',
  teacher: 'O‘qituvchi',
  salary: 'Maosh',
  commission: 'O‘qituvchi foizi',
  financialPeriod: 'Moliyaviy oy',
  recurringExpense: 'Takroriy xarajat',
  setting: 'Sozlama',
  employee: 'Xodim (HR)',
  account: 'Kassa',
  transaction: 'Moliyaviy yozuv',
  income: 'Tushum',
  expense: 'Xarajat',
  budget: 'Budjet',
  alert: 'Ogohlantirish',
  target: 'Sotuv rejasi',
  settings: 'Sozlamalar',
};

/** Xavfli yoki diqqat talab qiladigan amallar — ro‘yxatda ajratib ko‘rsatiladi */
export const AUDIT_CRITICAL_ACTIONS: readonly string[] = [
  'auth.login_failed',
  'auth.login_locked',
  'auth.refresh_token_reuse',
  'user.deleted',
  'role.deleted',
  'role.permissions_updated',
  'lead.deleted',
  'course.deleted',
  'group.deleted',
  'student.deleted',
  'payment.deleted',
  'payment.refunded',
  'expense.approved',
  'expense.rejected',
  'expense.threshold_changed',
  'finance.period_closed',
  'finance.period_reopened',
  'user.password_reset_by_admin',
  'salary.approved',
  'salary.paid',
  'commission.reversed',
  'commission.carried_over',
  'salary.unlocked',
  'salary.adjustment_voided',
  'salary.advance_paid',
  'finance.transaction_voided',
  'income.voided',
  'expense.voided',

  'discount.granted',
  'discount.revoked',
  'referral.rewarded',
  'student.archived',
  'student.status_changed',
  'student.group_changed',
  'employee.updated',
  'employee.leave_approved',
  'automation.rule_updated',
  'audit.settings_updated',
];

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action;
}

export function auditEntityLabel(entityType: string): string {
  return AUDIT_ENTITY_LABELS[entityType] ?? entityType;
}
